data:
  scale: 2
  n_colors: 1
  rgb_range: 1
  num_workers: 3
  pin_memory: False

  train:
    - name: 'DIV2KRAM'
      params:
        base_dir: '/media/Storage2/ldz/OSRT-master2/lau_dataset/odisr'
        augment: True
        patch_size: 192
        data_range: '1-800'
        test_every: 1000

  valid:
    - name: 'DIV2K'
      params:
        base_dir: '/media/Storage2/ldz/OSRT-master2/lau_dataset/odisr'
        augment: False
        patch_size: 192
        data_range: '801-810'

  test:
    - name: 'odisr'
      params:
        base_dir: '/media/Storage2/ldz/OSRT-master2/lau_dataset/odisr/validation'
    - name: 'sunset'
      params:
        base_dir: '/media/Storage2/ldz/OSRT-master2/lau_dataset/sun_test'



train:
 dir: './results/fsrcnn/'


